import React, { useState } from 'react'
import { api } from '../../api.js'
import { ErrorBox } from '../../components/Layout.jsx'

export default function FlagsTab({ caseId, flags, onChanged }) {
  const [error, setError] = useState(null)

  const acknowledge = async (id) => {
    try { await api(`/cases/flags/${id}/acknowledge`, { method: 'POST' }); onChanged() }
    catch (e) { setError(e.message) }
  }
  const recheck = async () => {
    try { await api(`/cases/${caseId}/evaluate-rules`, { method: 'POST' }); onChanged() }
    catch (e) { setError(e.message) }
  }

  const open = flags.filter((f) => !f.acknowledged)
  const acked = flags.filter((f) => f.acknowledged)

  return (
    <div>
      <ErrorBox error={error} />
      <div className="flex items-center justify-between mb-3">
        <p className="text-xs text-slate-500 max-w-2xl">
          Flags are generated by a rules engine from published guideline summaries. They are prompts for
          questions to raise with your treating oncologist — not recommendations.
        </p>
        <button className="btn-secondary" onClick={recheck}>Re-check now</button>
      </div>

      {open.length === 0 && <div className="card text-sm text-slate-500 mb-4">No open flags.</div>}

      {open.map((f) => (
        <FlagCard key={f.id} flag={f} onAck={() => acknowledge(f.id)} />
      ))}

      {acked.length > 0 && (
        <>
          <h3 className="font-semibold text-sm text-slate-500 mt-6 mb-2">Acknowledged</h3>
          {acked.map((f) => <FlagCard key={f.id} flag={f} muted />)}
        </>
      )}
    </div>
  )
}

function FlagCard({ flag, onAck, muted }) {
  const isGap = flag.flag_type === 'coverage_gap'
  return (
    <div className={`card mb-3 ${muted ? 'opacity-60' : ''} ${isGap ? 'border-l-4 border-l-purple-500' : 'border-l-4 border-l-red-500'}`}>
      <div className="flex justify-between items-start gap-3">
        <div>
          <span className={`text-xs font-bold uppercase ${isGap ? 'text-purple-600' : 'text-red-600'}`}>
            {isGap ? 'Coverage gap' : 'Decision risk'}
          </span>
          {flag.rule ? (
            <>
              <p className="font-medium mt-1">{flag.rule.condition_description}</p>
              <p className="text-sm text-slate-600 mt-1"><strong>Option this may foreclose:</strong> {flag.rule.foreclosed_option}</p>
              <p className="text-xs text-slate-500 mt-2">
                Source: <em>{flag.rule.source_guideline}</em> — {flag.rule.source_citation}
              </p>
            </>
          ) : (
            <p className="text-sm text-slate-700 mt-1 whitespace-pre-line">{flag.message}</p>
          )}
          <p className="text-[10px] text-slate-400 mt-1">Triggered {new Date(flag.triggered_at).toLocaleString()}</p>
        </div>
        {!muted && onAck && <button className="btn-secondary shrink-0" onClick={onAck}>Acknowledge</button>}
      </div>
    </div>
  )
}
